### ISSUE TITLE
2 Suggenstions

### ISSUE THREAD

**Issue by jardleex** [ykuksenko/ansible.nut#1]
Hello @ykuksenko,

first, thank you for this role. Even after 3 years it's the only one considerable to use for a NUT setup.

# 1 Support Ubuntu
As my systems run with Ubuntu I'd like to copy `vars/Debian.yml` to `vars/Ubuntu.yml`. I have tested this simple copy method with Ubuntu 16.04.6 and it worked just fine.
Do you want to place the copy or do you like to have a PR?

# 2 Support multiple equal options in upsmon.conf
Currently something like this is not possible with the role
```yaml
nut_upsmon_conf:
  FINALDELAY: 5
  MONITOR:
    - "ups01@10.11.12.13:3493 1 monslave password slave"
  NOTIFYMSG: 'ONLINE "UPS %s: On line power."'
  NOTIFYMSG: 'ONBATT "UPS %s: On battery."'
  NOTIFYMSG: 'LOWBATT "UPS %s: Battery is low."'
  NOTIFYMSG: 'REPLBATT "UPS %s: Battery needs to be replaced."'
  NOTIFYMSG: 'FSD "UPS %s: Forced shutdown in progress."'
  NOTIFYMSG: 'SHUTDOWN "Auto logout and shutdown proceeding."'
  NOTIFYMSG: 'COMMOK "UPS %s: Communications (re-)established."'
  NOTIFYMSG: 'COMMBAD "UPS %s: Communications lost."'
  NOTIFYMSG: 'NOCOMM "UPS %s: Not available."'
  NOTIFYMSG: 'NOPARENT "upsmon parent dead, shutdown impossible."'
```
Only the last line gets placed. [Source](http://rogerprice.org/NUT/ConfigExamples.A5.pdf)
This effectively breaks the use of any repeatable option in NUT. I'm running a sever/client based setup and need to adjust the clients actions on shutdown.
Any idea how to improve the loop in `upsmon.conf.j2` to support repeating lines?

Best regards

jardleex

**Comment by jardleex** [comment]
Solution for #2
```
nut_upsmon_conf:
  MONITOR:
    - "ups01@10.11.12.13:3493 1 monslave password slave"
  NOTIFYMSG:
    - 'ONLINE "UPS %s: On line power."'
    - 'ONBATT "UPS %s: On battery."'
    - 'LOWBATT "UPS %s: Battery is low."'
    - 'REPLBATT "UPS %s: Battery needs to be replaced."'
    - 'FSD "UPS %s: Forced shutdown in progress."'
    - 'SHUTDOWN "Auto logout and shutdown proceeding."'
    - 'COMMOK "UPS %s: Communications (re-)established."'
    - 'COMMBAD "UPS %s: Communications lost."'
    - 'NOCOMM "UPS %s: Not available."'
    - 'NOPARENT "upsmon parent dead, shutdown impossible."'
```

Sorry for bothering.

Leaving only #1 open.

**Comment by ykuksenko** [comment]
I am glad you found it useful!
PR for `#1` would be great. (First time I will be accepting one - so this is exciting!)

It has been a while since I looked at this. While I was trying to comprehend `#2`, I noticed the example on the `README.md` file probably has an issue like `#2`.
```
      nut_upsd_users:
        admin:
          password: password1
          actions: set
          actions: fsd
          instcmds: all
```
Namely actions will end up being just `fsd` instead of both. At the moment this is more of an FYI. I don't have a setup to test at the moment. After glancing at the template, converting the options dict for admin to a list should probably fix it.

Thank you for your contribution!
